[project]
name = "smartio-agv"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "alexang23", email = "alex1385.ang@gmail.com" }
]
requires-python = ">=3.14.6"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "passlib[bcrypt]",
    "colorlog",
    "pyserial",
    "schedule",
    "paho-mqtt",
    "python-multipart",
    "bcrypt<=4.0.1",
    "psutil",
    "requests",
    "zeep",
    "pywin32",
    "pydantic",
    "pydantic-settings",
    "another-fastapi-jwt-auth",
    "pytest",
    "pyserial-asyncio>=0.6",
]

[tool.uv]
package = false
