from database import Base
from sqlalchemy import Column, String, Boolean, ForeignKey, Integer, Enum, DateTime

from dataclasses import dataclass
from sqlalchemy.orm import relationship

from sqlalchemy.sql import func
from datetime import datetime

@dataclass
class Message(Base):
    __tablename__ = 'message'
    id: int = Column(Integer, primary_key=True, index=True, autoincrement=True, nullable=False)
    port_id: str = Column(String(128), nullable=False)
    port_no: int = Column(Integer, nullable=False)
    dual_port: int = Column(Integer, nullable=False)
    type: int = Column(Integer, nullable=False)
    stream: int = Column(Integer, nullable=False)
    function: int = Column(Integer, nullable=False)
    code_id: int = Column(Integer, nullable=False)
    sub_id: int = Column(Integer, nullable=False)
    msg_text: str = Column(String(256), nullable=True)
    status: str = Column(String(512),  nullable=True)
    occurred_at: datetime = Column(DateTime(timezone=True), nullable=False)
    created_at: datetime = Column(DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now())
    # updated_at: datetime = Column(DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now(), onupdate=func.now())


# @dataclass
# class Permission(Base):
#     __tablename__ = 'permission'

#     code: str = Column(String(128), primary_key=True)
#     name: str = Column(String(256), default='None', server_default='None', nullable=False)
#     created_at: datetime = Column(DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now())
#     updated_at: datetime = Column(DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now(), onupdate=func.now())

# @dataclass
# class AccountTypePermission(Base):
#     __tablename__ = 'account_type_permission'

#     acc_type: str = Column(String(128), ForeignKey('account_type.acc_type'), primary_key=True, nullable=False)
#     code: str = Column(String(128), ForeignKey('permission.code'), primary_key=True, nullable=False)
#     permission = Column(Enum('view', 'edit', 'all', 'off', 'hide'), default='view', server_default='view', nullable=False)
#     created_at: datetime = Column(DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now())
#     updated_at: datetime = Column(DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now(), onupdate=func.now())

#     permission_data: Permission = relationship(
#         'Permission',
#         backref='permission.code',
#         innerjoin=True,
#         cascade='all',
#         uselist=False
#     )
#     # @validates('status')
#     # def convert_lower(self, key, value):
#     #     return value.lower()

# @dataclass
# class AccountType(Base):
#     __tablename__ = 'account_type'

#     acc_type: str = Column(String(128), primary_key=True)
#     name: str = Column(String(256), default='None', server_default='None', nullable=False)
#     created_at: datetime = Column(DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now())
#     updated_at: datetime = Column(DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now(), onupdate=func.now())

#     permissions: AccountTypePermission = relationship(
#         'AccountTypePermission',
#         backref='account_type_permission.acc_type',
#         innerjoin=True,
#         cascade='all'
#     )

# @dataclass
# class User(Base):
#     __tablename__ = 'user'
#     id: int = Column(Integer, primary_key=True, index=True, autoincrement=True, nullable=False)
#     userid: str = Column(String(128), unique=True, nullable=False)
#     name: str = Column(String(256),  nullable=False)
#     password: str = Column(String(256), nullable=False)
#     active: bool = Column(Boolean(), default=True, server_default='1', nullable=False)
#     created_at: datetime = Column(DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now())
#     updated_at: datetime = Column(DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now(), onupdate=func.now())
    
#     acc_type: str = Column(String(128), ForeignKey('account_type.acc_type'), nullable=False)

#     account_types: AccountType = relationship(
#         'AccountType',
#         backref='account_type.acc_type',
#         cascade='all'
#     )
    
#     idx: int = Column(Integer, primary_key=True, index=True,
#                         server_default=text("GENERATED BY DEFAULT ON NULL AS IDENTITY") if engine.dialect.name == "oracle" else None, autoincrement=True)
#     user_id: str = Column(String(200), unique=True, nullable=False)
#     password_hash: str = Column(String(200), nullable=False)
#     user_type: str = Column(String(200), ForeignKey('groups.user_type'), nullable=False)
#     is_active: bool = Column(Boolean)
#     created_at: datetime = Column(DateTime(timezone=True), default=datetime.utcnow,
#                                     server_default=text('CURRENT_TIMESTAMP'))
#     updated_at: datetime = Column(DateTime(timezone=True), default=datetime.utcnow,
#                                     server_default=text('CURRENT_TIMESTAMP'), onupdate=datetime.utcnow)

#     group = relationship("DBGroup", back_populates="users")  # New relationship to DBGroup
    
# @dataclass
# class DBGroup(Base):
#     # create __tablename__ attribute, 宣告 model 對應的 database table name
#     __tablename__ = 'groups'

#     idx: int = Column(Integer, primary_key=True, index=True, server_default=text("GENERATED BY DEFAULT ON NULL AS IDENTITY") if engine.dialect.name == "oracle" else None, autoincrement=True)
#     user_type: str = Column(String(200), nullable=False, unique=True)  # Add unique constraint
#     created_at: datetime = Column(DateTime(timezone=True), default=datetime.utcnow)
#     updated_at: datetime = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)

#     users = relationship("DBUser", back_populates='group')
#     permissions = relationship("DBGroupPermission", back_populates='group')


# @dataclass
# class DBGroupPermission(Base):
#     # create __tablename__ attribute, 宣告 model 對應的 database table name
#     __tablename__ = 'group_permissions'

#     idx: int = Column(Integer, primary_key=True, index=True, server_default=text("GENERATED BY DEFAULT ON NULL AS IDENTITY") if engine.dialect.name == "oracle" else None, autoincrement=True)
#     permission_name: str = Column(String(200), nullable=False)
#     permission_action: str = Column(String(200), index=True, nullable=False)
#     permission_enable: bool = Column(Boolean, default=False)
#     user_type: str = Column(String(200), ForeignKey('groups.user_type'))

#     group = relationship("DBGroup", back_populates='permissions')

#     __table_args__ = (
#         UniqueConstraint('user_type', 'permission_action', name='uq_group_permission'),
#         ForeignKeyConstraint(['user_type'], ['groups.user_type'])  # Add foreign key constraint
#     )

